import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

export const WORKFLOW_PATH = path.join('.github', 'workflows', 'agentforge-ci.yml');

const WORKFLOW = `# Generated by AgentForge
name: AgentForge CI

on:
  pull_request:

permissions:
  contents: read

jobs:
  agentguard:
    name: AgentGuard security scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # \`agentforge scan\` exits with code 1 when it finds any risk in CLAUDE.md,
      # AGENTS.md or agent skills (HIGH or MEDIUM), which fails this job and
      # blocks the PR. To enforce the block, mark this check as required in
      # your branch protection rules.
      - name: Run AgentGuard scan
        run: npx -y @denizprof/agentforge scan
`;

/**
 * Writes `.github/workflows/agentforge-ci.yml`. Never overwrites an existing
 * workflow: resolves false if it already exists, true if created.
 */
export async function generateGitHubAction(cwd: string): Promise<boolean> {
  const file = path.join(cwd, WORKFLOW_PATH);
  await mkdir(path.dirname(file), { recursive: true });

  try {
    await writeFile(file, WORKFLOW, { encoding: 'utf8', flag: 'wx' });
    return true;
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === 'EEXIST') return false;
    throw err;
  }
}
