const IGNORE_PATTERNS = [
  'node_modules',
  'dist',
  'build',
  '.git',
  '.next',
  'coverage',
  'venv',
  '__pycache__',
  '*.min.js',
  '*.map',
  'package-lock.json',
  'yarn.lock',
];

export function generateIgnoreRules(): string {
  return [
    '# Generated by AgentForge - aggressive ignore rules to save tokens',
    ...IGNORE_PATTERNS,
    '',
  ].join('\n');
}

export function generateOptimizationInstructions(): string {
  return [
    'TOKEN OPTIMIZATION RULES:',
    '1. NEVER output full files for 1-line changes. Use surgical line replacements.',
    '2. DO NOT read minified or build files.',
    '3. Keep explanations strictly under 2 sentences unless asked.',
    '',
  ].join('\n');
}
